"""Cookbook FastAPI application."""

__cookbook__ = "01-first-agent-on-nebius"
__deployment_target__ = "clever-cloud"
__deployment_marker__ = "cookbook-01"
__deploy_guard__ = "frontend-skip"
__deploy_note__ = "telemetry-disabled"
__deploy_app_id_mode__ = "frontend-only"
__deploy_app_id_source__ = "github-actions"
__public_backend_url__ = "https://nebius-partners-cookbook-one.cleverapps.io"
__local_backend_url__ = "http://localhost:8000"
__mapped_cookbook_backends__ = "01-03"
__backend_domain_refresh__ = "02-03"
__latest_backend_mapping__ = "04"
__redeploy_pair__ = "01-04"
__pinecone_namespace_fix__ = "default"
__version__ = "0.1.0"
